var b = 2;

alert("a=b++");
alert(a=b++);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=++b");
alert(a=++b);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=--b")
alert(a=--b);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a+=b++");
alert(a+=b++);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=1; a+=++b");
var a = 1;
alert(a+=++b);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=1;a-=b++");
var a = 1;
alert(a-=b++);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=1;a-=++b");
var a = 1;
alert(a-=++b);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=1;a+=b--");
var a = 1;
alert(a+=b--);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
alert("a=1; a+=--b");
var a = 1;
alert(a+=--b);
alert("La valeur a =" +a);
alert("La valeur b =" +b);
